server:
   port: 9093
   servlet:
      context-path: /hrm
      
logging:
   level:
      org.hiernate.SQL: DEBUG
      org.springframework.web.client: TRACE
      org.springframework.http.client: DEBUG
      org.springframework.security: TRACE
      org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      
      
#NOT required here
#spring:
#   h2:
#      console:
#         enabled: true 
#         path: /h2-console
#   datasource:  
#      initialization-mode: true